name:                memory-optics
version:             0.1.0.0
github:              "ddddanil/memory-optics"
license:             BSD-3-Clause
author:              "Danil Doroshin"
maintainer:          "ddddanil5555@gmail.com"
copyright:           "2024 Danil Doroshin"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/memory-optics#readme>

language: GHC2021

default-extensions:
- NoImplicitPrelude
- NoFieldSelectors
- TemplateHaskell
- QuasiQuotes
- PatternSynonyms
- LambdaCase
- BlockArguments
- GADTs
- DataKinds
- TypeFamilies
- GHCForeignImportPrim
- UnliftedFFITypes
- UnboxedTuples

dependencies:
- base >= 4.7 && < 5
- lens
- polysemy
- polysemy-plugin
- type-level-numbers
- mmorph

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints
- -fplugin=Polysemy.Plugin

custom-setup:
  dependencies:
    - base
    - Cabal
    - Cabal-syntax

library:
  source-dirs: src

tests:
  memory-optics-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - memory-optics
    - resourcet
    - tasty
    - tasty-hedgehog
    - polysemy-test
    - hedgehog
